import Head from 'next/head'
import Layout from '../components/Layout'
import { useUser } from '@auth0/nextjs-auth0'
import useSWR from 'swr';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import SideBar from '../components/SideBar';
import DashboardOption from '../components/DashboardOption';

export default function Home() {
  const user = useUser();
  const [ watchlist, setWatchlist ] = useState(null);
  const [ page, setPage ] = useState("Watchlist");
  
  useEffect(() => {
    async function getData() {
      if (!user.isLoading) {
        var userInfo = await fetch(`/api/user/email/'${user.user.email}'`);
        userInfo = await userInfo.json();

        var body = {
          user: userInfo.res,
        }
    
        const options = {
          method: 'POST',
          headers: {
              'Content-Type': 'application/json',
          },
          body: JSON.stringify(body)
        };
    
        var response = await fetch('/api/user/get-watchlist', options);
        response = await response.json();
        setWatchlist(response);
      }
    }

    getData();
  }, [user.isLoading, user.user])

  if (user.isLoading) return <div>Loading...</div>
  if (user.error) return <div>Error!</div>
  if (!user.user) {
    window.location.href = '/landing';
  }

  let watchlistHTML, tvlistHTML;
  if (watchlist) {
    watchlistHTML = (
      <div className='flex flex-row'>
        {
          watchlist.movieres.map((element) => (
            <div key={element.details.title} className='relative w-[15vw]'>
              <Link href={"/movie/" + element.id}>
                <a>
                  <Image src={"https://image.tmdb.org/t/p/w500" + element.details.poster_path} alt={element.details.title} width={300} height={450} layout='raw'
                    className='rounded-3xl' />
                </a>
              </Link>
            </div>
          ))
        }
      </div>
    )

    tvlistHTML = (
      <div className='flex flex-row'>
        {
          watchlist.showres.map((element) => (
            <div key={element.details.name} className='relative w-[15vw]'>
              <Link href={"/series/" + element.id}>
                <a>
                  <Image src={"https://image.tmdb.org/t/p/w500" + element.details.poster_path} alt={element.details.name} width={300} height={450} layout='raw'
                    className='rounded-3xl' />
                </a>
              </Link>
            </div>
          ))
        }
      </div>
    )
  }

  console.log(page);
  const updateChoice = (option) => {
    setPage(option);
  }

  return (
    <Layout>
      <div>
        <Head>
          <title>Mimir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div className='flex'>
            
            <SideBar handler={updateChoice} />

            <DashboardOption page={page} />

            {/* <div className='ml-4 w-full'>
              <div className='text-center'>
                <h1 className='text-3xl py-4'>Movies on your watchlist</h1>
                { watchlistHTML }
              </div>

              <div className='text-center mt-4'>
                <h1 className='text-3xl py-4'>TV Shows Tracked</h1>
                { tvlistHTML }
              </div>
            </div> */}
          </div>
        </main>
      </div>
    </Layout>
  )
}
