import Head from 'next/head'
import Layout from '../components/Layout'
import { useUser } from '@auth0/nextjs-auth0'

export default function Home() {
  const user = useUser();

  if (user.isLoading) return <div>Loading...</div>
  if (user.error) return <div>Error!</div>
  if (!user.user) {
    window.location.href = '/landing';
  }

  return (
    <Layout>
      <div>
        <Head>
          <title>Ramedia</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          
        </main>
      </div>
    </Layout>
  )
}
