import Head from 'next/head'
import Layout from '../components/Layout'
import useSWR from 'swr'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Movies.module.css'
import { useEffect, useState } from 'react'

const fetcher = url => fetch(url).then(res => res.json())

export default function MoviesHome() {

  const { data, error } = useSWR('/api/trending-movies', fetcher)
  const [ slideIndex, setSlideIndex ] = useState(1);

  useEffect(() => {
    showSlides(slideIndex);
  })

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  function handleRightClick() {
    if (slideIndex + 1 > 10) {
      setSlideIndex(1);
    } else {
      setSlideIndex(slideIndex + 1);
    }
  }

  function handleLeftClick() {
    if (slideIndex - 1 < 1) {
      setSlideIndex(10);
    } else {
      setSlideIndex(slideIndex - 1);
    }
  }

  function showSlides(n) {
    let slides = document.getElementsByClassName(`${styles.mySlides}`);
    let dots = document.getElementsByClassName(`${styles.dot}`);
    let currSlide = document.getElementById(slideIndex - 1);

    for (let i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (let i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(` ${styles.active}`, "");
    }
    if (slides[slideIndex-1]) {
      slides[slideIndex-1].style.display = "block";
    }
    if (dots[slideIndex-1]) {
      dots[slideIndex-1].className += ` ${styles.active}`;
    }

    if (data) {
      document.getElementById('title').innerHTML = data.popular[slideIndex - 1].movie.title;
    }

    setTimeout(handleRightClick, 6000);
  }

  function handleScrollLeft() {
    let div = document.getElementById('card-Container');
    div.scrollBy({
      left: -screen.width,
      behavior: 'smooth'
    });
  }

  function handleScrollRight() {
    let div = document.getElementById('card-Container');
    div.scrollBy({
      left: screen.width,
      behavior: 'smooth'
    });
  }

  console.log(data);

  return (
    <Layout>
      <div>
        <Head>
          <title>Ramedia</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='scroll-smooth'>
          <div className='flex justify-center py-12'>
            <h1 className='text-5xl font-semibold tracking-wider'>Movies</h1>
          </div>

          <div className='flex flex-row'>
            <div className='w-3/4 relative z-30'>
              {
                data.popular.map((element) => (
                  <div key={element.movie.title} id={data.popular.indexOf(element)} className={`${styles.mySlides} ${styles.fade}`}>
                    <Image src={element.movie.imageurl} alt={element.movie.title} width={1493} height={839} priority layout='raw' className='w-full rounded-r-3xl shadow-[4px_4px_10px_0px_rgba(0,0,0,0.5)]' />
                  </div>
                ))
              }

              <a className={styles.prev} onClick={handleLeftClick}>&#10094;</a>
              <a className={styles.next} onClick={handleRightClick}>&#10095;</a>

              <div className='absolute bottom-4 left-2/4'>
                <div className='relative -left-2/4 space-x-5'>
                  <span className={styles.dot} onClick={() => setSlideIndex(1)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(2)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(3)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(4)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(5)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(6)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(7)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(8)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(9)}></span>
                  <span className={styles.dot} onClick={() => setSlideIndex(10)}></span>
                </div>
              </div>
            </div>

            <div className='w-1/4 z-20 flex flex-col'>
              <h1 id='title' className='px-4 text-center text-3xl font-semibold tracking-wider' />
              <p></p>
              <div>

              </div>
            </div>
          </div>

          <div className='bg-[#FFE3CE] -translate-y-32 rounded-xl pt-44'>
            <h2 className='text-4xl font-semibold ml-10'>Trending Movies</h2>
            <div className='relative justify-center items-center'>

              <div id='card-Container' className='card-Container pt-8 pb-4 mb-4'>
                {
                  data.trending.map((element) => (
                    <div key={element.movie.title} className='card'>
                      <div className='transition hover:scale-105 cursor-pointer rounded-xl shadow-[4px_4px_10px_0px_rgba(0,0,0,0.75)]'>
                        <Link href={`/movie/${element.movie.ids.imdb}`}>
                          <a>
                            <Image src={element.movie.imageurl} alt={element.movie.title} width={300} height={450} priority layout='raw' className='w-full rounded-xl' />
                          </a>
                        </Link>
                      </div>
                      <div className='flex h-20 justify-center items-center'>
                        <h1 className='text-lg font-semibold text-ellipsis'>{element.movie.title}</h1>
                      </div>
                    </div>
                  ))
                }
              </div>

              <div className='absolute top-[40%] left-4 w-12 h-12 cursor-pointer bg-black flex justify-center items-center rounded-full shadow-[4px_4px_10px_0px_rgba(0,0,0,1)]' onClick={handleScrollLeft}>
                <a className='text-2xl font-semibold text-white select-none'>&#10094;</a>
              </div>
              <div className='absolute top-[40%] right-4 w-12 h-12 cursor-pointer bg-black flex justify-center items-center rounded-full shadow-[4px_4px_10px_0px_rgba(0,0,0,1)]' onClick={handleScrollRight}>
                <a className='text-2xl font-semibold text-white select-none'>&#10095;</a>
              </div>
            </div>
          </div>

          {/* <div className='flex justify-center mt-4'>
            <form action='/search' method='GET'
              className='h-16 w-2/4 bg-[#FF971D] opacity-80 rounded-full
                          flex items-center px-4
                          hover:opacity-100 focus-within:opacity-100
                          transition-all duration-200'>
              <button type="submit" value="Submit">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </button>
              <input type="text" id='search-text' name='keyword' placeholder="Search Movies"
                className='grow px-4 text-lg text-[#131313] font-sans font-medium placeholder:italic placeholder:text-[#131313] bg-[#FF971D] focus:outline-0'/>
            </form>
          </div> */}

          <div className='text-center mt-4'>

          </div>

          <div className='h-12 bg-teal-400 flex flex-row justify-center'>
            Movie Categories
          </div>
        </main>
      </div>
    </Layout>
  )
}