import { useUser } from '@auth0/nextjs-auth0'
import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image';

export default function Home() {

  const { user, error, isLoading } = useUser();
  console.log(user);

  if (isLoading) {
    return (
      <h1>Loading!</h1>
    )
  }

  if (user) {
    return (
      <Layout>
        <div>
          <Head>
            <title>Ramedia</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <main className='flex flex-col'>
            <div className='flex flex-row justify-center space-x-4'>
              <div className='w-32 h-32 relative'>
                <Image
                  src={user.picture}
                  alt={user.name}
                  layout='fill'
                  quality={100}
                  priority
                  className='w-32 h-32 rounded-full'
                />
              </div>
              <div className='flex items-center'>
                <h1 className='text-3xl'>{user.nickname}</h1>
              </div>
            </div>
          </main>
        </div>
      </Layout>
    )
  } else {
    window.location.href = '/';
  }
}
