import { useUser } from '@auth0/nextjs-auth0'
import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

function profile() {
  const user = useUser();
  if (user.isLoading || isLoading) {
    return (
      <h1>Loading!</h1>
    )
  }
  if (!user.user) {
    window.location.href = '/';
  }

  const router = useRouter();
  const [data, setData] = useState(null);
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    fetch('/api/trakt/trakt_authorize')
      .then((res) => res.json())
      .then((data) => {
        setData(data)
        setLoading(false)
      })
  }, [])

  const code = router.query.code;
  if (code) {
    console.log(code)
    getToken();
  }

  async function getToken() {
    let codeData = { user_code: code }
    let response = await fetch('/api/trakt/trakt_gettoken', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(codeData)
    });
    response = await response.json();
    console.log(response);
  }

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No profile data</p>

  console.log(data);

  return (
    <Layout>
      <div>
        <Head>
          <title>Ramedia</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='flex flex-col items-center'>
          <div className='flex flex-row justify-center space-x-4'>
            <div className='w-32 h-32 relative'>
              <Image
                src={user.user.picture}
                alt={user.user.name}
                layout='fill'
                quality={100}
                priority
                className='w-32 h-32 rounded-full'
              />
            </div>
            <div className='flex items-center'>
              <h1 className='text-3xl'>{user.user.nickname}</h1>
            </div>
          </div>

          <div className='w-32 h-20 flex text-center'>
            <Link href={data.link}>
              <a className="rounded-md px-3 py-2 hover:bg-[#FFE8D6] flex items-center">Connect to Trakt</a>
            </Link>
          </div>
        </main>
      </div>
    </Layout>
  )
}

export default profile;
