import { useUser, withPageAuthRequired } from '@auth0/nextjs-auth0'
import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image';
import { useRouter } from 'next/router';
import Trakt_Button from '../components/profile/Trakt_Button';
import { useEffect } from 'react';
import { useState } from 'react';
import { WithPageAuthRequired } from '@auth0/nextjs-auth0';

export default withPageAuthRequired(function Profile({ user }) {

  return (
    <Layout>
      <div>
        <Head>
          <title>Mimir</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='flex flex-col items-center'>
          <div className='flex flex-row justify-center space-x-4'>
            <div className='w-32 h-32 relative'>
              <Image
                src={user.picture}
                alt={user.name}
                layout='fill'
                quality={100}
                priority
                className='w-32 h-32 rounded-full'
              />
            </div>
            <div className='flex items-center'>
              <h1 className='text-3xl'>{user.nickname}</h1>
            </div>
          </div>

          <Trakt_Button />

        </main>
      </div>
    </Layout>
  )
});