import Head from 'next/head'
import Layout from '../components/Layout'
import useSWR from 'swr'
import Link from 'next/link'
import Image from 'next/image'

const fetcher = url => fetch(url).then(res => res.json())

export default function MoviesHome() {

  const { data, error } = useSWR('/api/trendingShows', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  console.log(data);

  return (
    <Layout>
      <div>
        <Head>
          <title>Ramedia</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className='overflow-x-hidden'>
          <div className='w-[70vw] left-[15vw] bg-neutral-500 relative flex gap-2 snap-x snap-mandatory overflow-x-auto z-0'>
            {
              data.popular.map((element) => (
                <div key={element.title} className='snap-center shrink-0 w-[70vw]'>
                  <Image src={element.imageurl} alt={element.title} width={1493} height={839} className='' />
                </div>
              ))
            }
          </div>

          <div className='flex justify-center mt-4'>
            <form action='/search' method='GET'
              className='h-16 w-2/4 bg-[#FF971D] opacity-80 rounded-full
                          flex items-center px-4
                          hover:opacity-100 focus-within:opacity-100
                          transition-all duration-200'>
              <button type="submit" value="Submit">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </button>
              <input type="text" id='search-text' name='keyword' placeholder="Search Movies"
                className='grow px-4 text-lg text-[#131313] font-sans font-medium placeholder:italic placeholder:text-[#131313] bg-[#FF971D] focus:outline-0'/>
            </form>
          </div>

          <div className='text-center mt-4'>
            <h2 className='text-4xl font-semibold text-[#303841]'>Trending Movies</h2>
            <div className='card-Container pt-8 mb-4'>
              {
                data.trending.map((element) => (
                  <div key={element.show.title} className='card'>
                    <Link href={`/series/${element.show.ids.imdb}`}>
                      <a>
                        <Image src={element.show.imageurl} alt={element.show.title} width={300} height={450} className='w-16 rounded-xl' />
                        <h1 className='text-lg font-semibold px-2 h-14 overflow-hidden text-ellipsis text-[#303841]'>{element.show.title}</h1>
                      </a>
                    </Link>
                  </div>
                ))
              }
            </div>
          </div>

          <div className='h-12 w-screen bg-teal-400 flex flex-row justify-center'>
            Movie Categories
          </div>
        </main>
      </div>
    </Layout>
  )
}