import Layout from '../../components/Layout';
import Head from 'next/head';
import { useRouter } from 'next/router';
import useSWR from 'swr';
import { useEffect } from 'react';
import Image from 'next/image';

const fetcher = url => fetch(url).then(res => res.json())

export default function SeriesPage() {
  const router = useRouter();

  const { data, error } = useSWR(`/api/getSeriesData?imdb_id=${router.query.id}`, fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  console.log(data);

  var background;
  if (data.artRes.status != "error") {
    var backgroundURL;
    if (data.artRes.showbackground) {
      backgroundURL = data.artRes.showbackground[0].url;
    } else {
      backgroundURL = data.artRes.hdshowlogo[0].url;
    }
    background = (
      <div className='w-[1493px] h-[839px] flex justify-center items-center'>
        {/* <img src={backgroundURL} className='z-0' /> */}
        <Image src={backgroundURL} alt={data.result.name} width={1493} height={839} className="z-0" />
      </div>
    );
  } else {
    background = (
      <div className='w-[1493px] h-[839px] flex justify-center items-center'>
        <h1 className='text-4xl'>Image not available!</h1>
      </div>
    );
  }

  return (
    <Layout>
      <div>
        <Head>
          <title>Ramedia</title>
            <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className='bg-yellow-300 z-0 relative'>
            { background }
            <div className='absolute bottom-0 left-0 w-screen h-32 bg-gradient-to-t from-[#F9F6F7] z-50' />
          </div>

          <div className='flex space-x-2 z-10 mt-4 px-4'>
            <div className='flex-none w-4/12 flex justify-center'>
              {/* <img src={"https://image.tmdb.org/t/p/w300" + data.result.poster_path} className='rounded-lg' /> */}
              <Image src={"https://image.tmdb.org/t/p/w300" + data.result.poster_path} alt={data.result.name} width={300} height={450} className='rounded-lg' />
            </div>

            <div className='flex flex-col'>
              <div className='grow'>
                <div className='text-center mb-8'>
                  <h1 className='text-5xl py-2'>{data.result.name}</h1>
                </div>

                <div className='flex flex-row'>
                  <div className='w-8/12'>
                    <p className='px-4 text-xl'>
                      {data.result.overview}
                    </p>
                  </div>
                  <div className='w-4/12 text-center flex flex-col'>
                    <h2 className='text-3xl'>Average User Rating:</h2>
                    <p className='text-2xl'>{data.result.vote_average}/10</p>
                  </div>
                </div>
              </div>

              <div className='grow flex flex-row justify-center items-center'>
                <div className='flex flex-col justify-center items-center w-3/12 space-y-4'>
                  <h3>Seen this movie?</h3>
                  <button className='w-16 h-12 bg-green-400 rounded-full'>
                    Yes
                  </button>
                </div>

                <div className='flex flex-col justify-center items-center w-3/12 space-y-4'>
                  <h3>Add to Favorites</h3>
                  <button className='w-16 h-12 bg-orange-400 rounded-full'>
                    Yes
                  </button>
                </div>
              </div>

            </div>
          </div>

        </main>
      </div>
    </Layout>
  )
}